#ifndef SYSCFG_INTERFACE_H
#define SYSCFG_INTERFACE_H

typedef enum{
	SYSCFG_PORTA=0,
	SYSCFG_PORTB,
	SYSCFG_PORTC,
	SYSCFG_PORTD,
	SYSCFG_PORTE,
	SYSCFG_PORTF,
	SYSCFG_PORTG,
	SYSCFG_PORTH
}SYSCFG_Port_t;

typedef enum
{
	SYSCFG_PIN0,
	SYSCFG_PIN1,
	SYSCFG_PIN2,
	SYSCFG_PIN3,
	SYSCFG_PIN4,
	SYSCFG_PIN5,
	SYSCFG_PIN6,
	SYSCFG_PIN7,
	SYSCFG_PIN8,
	SYSCFG_PIN9,
	SYSCFG_PIN10,
	SYSCFG_PIN11,
	SYSCFG_PIN12,
	SYSCFG_PIN13,
	SYSCFG_PIN14,
	SYSCFG_PIN15

}SYSCFG_LineNum;

void SYSCFG_voidSetEXTIPort( SYSCFG_LineNum copy_PinNum, SYSCFG_Port_t copy_port);


#endif
